### PR TITLE
[OXT-105] Fix Windows Build certificate signing issues 

### PR DESCRIPTION
**Pull request by DStaelens**
Fixes for ticket OXT-105 to correct signing issues

### CODE REVIEW

**Comment by cjp256** [comment]
Please follow commit guidelines.  Also, I think your tabs are mismatched in areas. Thanks!

**Comment by rossphilipson** [comment]
So this looks like the last version in the old PR so that is good. I guess the problems Kevin had were related to the type of cert he used and not a problem with this fix.

There was a large block near the comment "# copy back the new cat files alongside their inf files". You may have told me but why was this pulled out?

**Comment by DStaelens** [comment]
The copy back was copying over 32 bit files with 64 bit files with the same names, so some drivers if you tried to install them were the wrong platform.  If someone needs just the built sys files debugging they are already sitting in the xc-windows/build/<arch> directories so it's a bit redundant as well.

**Comment by rossphilipson** [comment]
Ok that sounds reasonable. Since Kevin actually tried this, I would like a +1 from him then I will merge it.

**Comment by rossphilipson** [comment]
Kevin says +1 on IRC - merging...

**Pull request merged**
