### PR TITLE
Reenable XenVesa PV Driver

### PR DESCRIPTION
**Pull request by meisners**
Also:
1. Do not call SynchronizeExecution in ReportPresentProgress() since we
have no INT
2. Change name of driver to one on whitelist
3. Change tag on memory allocs to XENGFX

This PR also addresses issues seen in OXT-318 and OXT-123.

Signed-off-by: Steve Meisner <meisners@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
LGTM +1

**Comment by jean-edouard** [comment]
Github won't diff xenVesaDO.inf, as it is UTF16...
Here's the diff:
```
--- a/xenVesaDO.inf	2015-11-30 12:37:41.158051302 -0500
+++ b/xenVesaDO.inf	2015-11-30 12:37:49.026051554 -0500
@@ -16,7 +16,7 @@
 Signature = "$Windows NT$"
 Class=Display
 ClassGUID={4d36e968-e325-11ce-bfc1-08002be10318}
-Provider=%MS%
+Provider=%PLATFORM%
 DriverVer= 03/15/2011, 0.03.15.0011
 CatalogFile=XenVesaDO.cat
 
@@ -35,21 +35,21 @@
 
 
 [Manufacturer]
-%MS%=MS,NTamd64,NTarm
+%PLATFORM%=%PLATFORM%,NTx86,NTamd64
 
-[MS]
+[OpenXT.NTx86]
 ;
 ;	Allow the driver to be loaded on VGA and XGA
 ;
-"Citrix Xen Display Driver" = XenVesaDO_Inst, PCI\CC_0300
-"Citrix Xen Display Driver" = XenVesaDO_Inst, PCI\CC_0301
+"OpenXT Display Driver" = XenVesaDO_Inst, PCI\CC_0300
+"OpenXT Display Driver" = XenVesaDO_Inst, PCI\CC_0301
 
-[MS.NTamd64]
+[OpenXT.NTamd64]
 ;
 ;	Allow the driver to be loaded on VGA and XGA
 ;
-"Citrix Xen Display Driver" = XenVesaDO_Inst, PCI\CC_0300
-"Citrix Xen Display Driver" = XenVesaDO_Inst, PCI\CC_0301
+"OpenXT Display Driver" = XenVesaDO_Inst, PCI\CC_0300
+"OpenXT Display Driver" = XenVesaDO_Inst, PCI\CC_0301
 
 
 [XenVesaDO_Inst]
@@ -73,8 +73,8 @@
 ;
 ;   Display Adapter Specific Settings
 ;
-[XenVesaDO.SoftwareSettings]
-AddReg = XenVesaDO_SoftwareDeviceSettings
+;[XenVesaDO.SoftwareSettings]
+;AddReg = XenVesaDO_SoftwareDeviceSettings
 
 [XenVesaDO_SoftwareDeviceSettings]
 HKR,, VgaCompatible,               %REG_DWORD%, 0
@@ -82,18 +82,18 @@
 [XenVesaDO.Files]
 XenVesaDO.sys
 
-[XenVesaDO_EventLog_Inst]
-AddReg = XenVesaDO_EventLog_Inst.AddReg
+;[XenVesaDO_EventLog_Inst]
+;AddReg = XenVesaDO_EventLog_Inst.AddReg
 
-[XenVesaDO_EventLog_Inst.AddReg]
-HKR,,EventMessageFile,%REG_EXPAND_SZ%,"%%SystemRoot%%\System32\IoLogMsg.dll"
-HKR,,TypesSupported,%REG_DWORD%,7
+;[XenVesaDO_EventLog_Inst.AddReg]
+;HKR,,EventMessageFile,%REG_EXPAND_SZ%,"%%SystemRoot%%\System32\IoLogMsg.dll"
+;HKR,,TypesSupported,%REG_DWORD%,7
 
 
 [Strings]
 
 ;  *******Localizable Strings*******
-MS= "Microsoft"
+PLATFORM = "OpenXT"
 Desc_Sample = "Data"
 
 ;  *******Non Localizable Strings*******
```

**Comment by jean-edouard** [comment]
Oh, and +1 :)

**Comment by rossphilipson** [comment]
Will merge soon....

**Pull request merged**
