### PR TITLE
Fix Windows Build certificate signing issues 

### PR DESCRIPTION
**Pull request by DStaelens**
During the build and cert signing process, files where getting renamed or overwritten after signing that would cause Windows 7X64 to blue screen because the boot drivers would show up with invalid signatures.   Built and tested on Windows 7 X64.

### CODE REVIEW

**Comment by pearsonk** [comment]
I merged this into my mirror and it did not work for me completely in a Win7_64 install. I still received popups citing unsigned drivers for:
Xen disk filter driver
XenSource VESA miniport
XenSource xenvbd SCSI miniport
OpenXT Xen PV Input Device

For S&Gs (since I used buildbot to do the guest tools) I went into the build tree and ensured that xc-windows was at commit 00a591e...
Windows 7 32-bit made no complaints.

Is there a JIRA ticket for this? I can attach the build output in case there is something in there but I don't see a reference in the commit message.

**Comment by rossphilipson** [comment]
I don't think there is a ticket. I assume you had your dev keys installed on the target? You are saying that just a few drivers failed to get signed right?

Oh yea, there probably should be a ticket too.

**Comment by rossphilipson** [comment]
https://openxt.atlassian.net/browse/OXT-105

**Comment by pearsonk** [comment]
Yes, I have my production keys on the target and quite a lot got signed, just apparently these 4. I will post the Windows build log to OXT-105

**Comment by rossphilipson** [comment]
This pull request is changes as DStaelens' adds work for other things. I think it is invalid at this point. There should be a clean PR for the signing fix and one for xenaud.

**Comment by DStaelens** [comment]
Separated as best as we could.  Merge sign fixes first.

**Pull request closed without merging**
