### PR TITLE
Remove use of V4V from WLAN driver

### PR DESCRIPTION
**Pull request by meisners**
OXT-883
OXT-1149

Signed-off-by: Steve Meisner <meisners@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/988

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/989
Works fine, merging soon.

**Comment by dpsmith** [comment]
A stable-7 PR probably would be good as well.

**Comment by jean-edouard** [comment]
@dpsmith https://github.com/OpenXT/xc-windows/pull/35

**Pull request merged**
