### PR TITLE
STABLE-9: Remove disk-related drivers from the build

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>
(cherry picked from commit 28bb8369f9dae10096ed59f7897b417ddb979f1e)
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by smeisner** [comment]
This change looks good.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6534

**Comment by crogers1** [comment]
OXT-1576

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6550

**Comment by stacktrust** [comment]
https://openxt.atlassian.net/browse/OXT-1559

**Pull request merged**
