### PR TITLE
[OXT-228] Ac97 windows driver

### PR DESCRIPTION
**Pull request by DStaelens**
Added driver project and add to build system and installer.  Related to work being done in qemu for audio bugs.

### CODE REVIEW

**Comment by pearsonk** [comment]
This seems to be an odd mix of adding a new xenaud driver and changes that seem to better fit with https://github.com/OpenXT/xc-windows/pull/16

Perhaps the changes such as the do_verify that pertain to signing can be rebased into the PR pertinent to driver signing adjustments.

**Comment by rossphilipson** [comment]
I think this is the same issue as before where github is determining what is in the PR as the delta between the source and target branch. DStaelens branches work well to avoid this problem. But yea, -1 in the current state.

**Comment by pearsonk** [comment]
Yes, the first commit in this PR is based on the dependency in the branches, but commit https://github.com/DStaelens/xc-windows/commit/5ab151573cc2689f3ef9e64d17273c96dff48484 has a mix of cert fixes as well as xenaud driver.

**Comment by rossphilipson** [comment]
Ah so there are 2 issues here. Right, I agree, that the first parts of https://github.com/DStaelens/xc-windows/commit/5ab151573cc2689f3ef9e64d17273c96dff48484 are not part of the audio driver commit.

**Comment by pearsonk** [comment]
Correct, and those parts are actually missing from the signing PR

**Comment by rossphilipson** [comment]
@DStaelens the headers in the windows sample code look good - you just need the original stub there to comply with MSLPL. I would remove the Citrix copyright from the INF files. We can handle any other rebranding issues later but we can't copyright those files.

**Comment by rossphilipson** [comment]
LGTM now, merging

**Pull request merged**
