### PR TITLE
Move xenvesado to its own folder

### PR DESCRIPTION
**Pull request by meisners**
This PR:
- moves the xenvesado driver into its own folder just like the other PV driver projects.
- fixes versioning info stamped in INF file to be the same as the other drivers.
- fixed build warnings ('#' instead of 'REM' in dobuild.bat) and (remove define of win32 in xengfx/wddm/display/sources)
- do_sign.ps1 now considers xenvesado.inf as a regular inf file

Note: folder xengfx/vesa is now gone. Miniport folder contents moved to toplevel xenvesado

### CODE REVIEW

**Comment by jean-edouard** [comment]
dobuild.bat had mixed line endings.
@meisners, you unified them to UNIX (LF), shouldn't they be Windows (CR+LF) instead?

**Comment by jean-edouard** [comment]
You also introduced mixed line endings in `xenvesado/miniport.vcxproj`.
The rest looks good, I'll merge and test this once my 2 comments are addressed.

**Comment by meisners** [comment]
Changed line endings to Unix in dobuild.bat ... and Windows in xenvesa/miniport.vcproj.

**Comment by jean-edouard** [comment]
LGTM now, will merge soon.

**Pull request merged**
